server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/restaurant-service?useUnicode=yes&useSSL=false&characterEncoding=UTF-8
    username: root
    password: root

  liquibase:
    change-log: classpath:db/db.changelog-master.xml
